### ISSUE TITLE
Name Error : name 'code' is not defined

### ISSUE THREAD

**Issue by dfengwin** [Svenskithesource/PyArmor-Unpacker#23]
thanks for your great work.
And, When try to unpack a PyArmor script, I came across an error like "Name Error : name 'code' is not defined" after the injection, with method2.
So, I did not get the "dump" directory and pyc file.  
I don't know why

**Comment by dfengwin** [comment]
<img width="297" alt="1665027854361" src="https://user-images.githubusercontent.com/37488623/194209470-a3cc566b-2af1-498a-bb63-dd4fe05a1817.png">

**Comment by dfengwin** [comment]
it seems like, this error have something to do with "line 465 : code = output_code(code)" of the "code.py".

**Comment by dfengwin** [comment]
sys._current_frames() has no return.

**Comment by Svenskithesource** [comment]
Can you send the file over? It looks like they have some anti debugging. Also what Python version is it, that could affect it as well.

**Comment by dfengwin** [comment]
got it

**Comment by Svenskithesource** [comment]
Got it as in you solved it? If so please tell me what the issue was. Or did you send me an email? (I haven't received one)

**Comment by dfengwin** [comment]
not yet, a zip file has been sent to your inbox

**Comment by 0xdf223** [comment]
What was the issue? I see this is closed, but no update, and I'm getting the same thing.

**Comment by Svenskithesource** [comment]
The issue was that he injected after the code had already finished. Please open a new issue if you have the same problem. Provide the files as well as details like the version etc.

**Comment by 0xdf223** [comment]
Sent you some details via the email above. I can open another issue if you like as well.

**Comment by OwnerCM** [comment]
> The issue was that he injected after the code had already finished. Please open a new issue if you have the same problem. Provide the files as well as details like the version etc.

@Svenskithesource Thank you for providing such a useful tool. I have a PyArmor encrypted py file running in Python version 3.8.16. When using method 2, I am encountering the same problem and do not know how to solve it.
The file has been uploaded as an attachment. I hope you can help me take a look when you have time. Thank you again!
[file.zip](https://github.com/Svenskithesource/PyArmor-Unpacker/files/12328662/file.zip)
