### ISSUE TITLE
The executable used python version 3.7 and closed immediately

### ISSUE THREAD

**Issue by 20521429** [Svenskithesource/PyArmor-Unpacker#29]
maybe i cant use any of 3 methods with that conditions
how i can handle it ?

**Comment by Svenskithesource** [comment]
You can use a debugger to pause it while it's running or you can see what packages it uses and hook/hijack those and pause in them so you have time to use method 1 or 2. You will have to change the detection script, if you scroll down you will see "tkinter" which you'll have to change with the name of the package that you replaced.

**Comment by Twi1ight-source** [comment]
i run `pyc` file and it also exits quickly, i didnt know how to debug `pyc` file, so i decompiled it  into `py`  file to debug, but when i use visual studio or pdb,... i cant inject

do you know any solution ?

**Comment by Svenskithesource** [comment]
> You can use a debugger to pause it while it's running or you can see what packages it uses and hook/hijack those and pause in them so you have time to use method 1 or 2. You will have to change the detection script, if you scroll down you will see "tkinter" which you'll have to change with the name of the package that you replaced.

Have you tried this? What were the issues with it?
