### ISSUE TITLE
ImportError: cannot import name 'pyarmor_runtime' from 'pytransform'

### ISSUE THREAD

**Issue by rrblgn** [Svenskithesource/PyArmor-Unpacker#32]
Greetings,
When I try to use "pip install pytransform" on Windows, I get errors about the MDAnalysis. So I decided to run it on Colab environment. However, this time even though pip installs pytransfrom well, I get: "ImportError: cannot import name 'pyarmor_runtime' from 'pytransform''" error. Can you assist me on overcoming this issue?

**Comment by Svenskithesource** [comment]
pytransform is something that is shipped with the Python script/executable. You can't get it from pip.

**Comment by rrblgn** [comment]
If I directly want to use the method#3, it raises this error: "ModuleNotFoundError: No module named 'pytransform'"

**Comment by rrblgn** [comment]
Oh thanks! I was decompiling an exe file and also using pycdc and i encountered the armored core when i used pycdc, so i went back to the pyz extracted files of the exe file and copied armor.py and pyc2py.py file and it worked here! Thank you for the script and I think different people can also encounter such problem so maybe you can make this issue visible.
