### ISSUE TITLE
Success but fails to save?

### ISSUE THREAD

**Issue by InternetMedicineMan** [Svenskithesource/PyArmor-Unpacker#34]
I'm getting an error like this on Method 3 because I can't figure out how to use a Python Injector on a Linux Server:

`Successfully unpacked the file, saving to disk now
Traceback (most recent call last):
  File "/despatcher/bypass.py", line 425, in log
    filename = code.co_filename.replace("<frozen ", '').replace(">", '')
AttributeError: 'tuple' object has no attribute 'co_filename'

Killed`

Seems like it's successful but can't save to disk? Object has no attribute?

**Comment by Svenskithesource** [comment]
This means that it's protected with a paid PyArmor mode which my unpacker doesn't support.
