### ISSUE TITLE
handle_armor_enter ValueError

### ISSUE THREAD

**Issue by hkhj326** [Svenskithesource/PyArmor-Unpacker#40]
Python 3.8.10 
Windows10

use Method2 unpack throw this error:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "<string>", line 457, in <module>
  File "<string>", line 233, in output_code
  File "<string>", line 233, in <genexpr>
  File "<string>", line 245, in output_code
  File "<string>", line 330, in handle_armor_enter
ValueError: byte must be in range(0, 256)

**Comment by Svenskithesource** [comment]
Hello, could you please print the byte that's trying to add/change?

**Comment by Svenskithesource** [comment]
This could be because the script detects the `fake_exit` wrong. You can change this to `fake_exit = 6` in the code. From experience that is the most common fake exit.

**Comment by Svenskithesource** [comment]
Can you show me the changes you made? Also, you cannot rely on pycdc as it is unstable. Even if the unpacking is perfect there is still a high chance of failure.

**Comment by w1redch4d** [comment]
```py
if argument == fake_exit:
                raw_code[i] = opcode.opmap[
                    "RETURN_VALUE"
                ]  # Got to use this because the variable is converted to bytes
                continue
```
to 
```py
if argument < try_start + 2:
                raw_code[i] = opcode.opmap["RETURN_VALUE"] # Got to use this because the variable is converted to bytes
                continue
 ```
 should work

**Comment by OwnerCM** [comment]
> ```python
> if argument == fake_exit:
>                 raw_code[i] = opcode.opmap[
>                     "RETURN_VALUE"
>                 ]  # Got to use this because the variable is converted to bytes
>                 continue
> ```
> 
> to
> 
> ```python
> if argument < try_start + 2:
>                 raw_code[i] = opcode.opmap["RETURN_VALUE"] # Got to use this because the variable is converted to bytes
>                 continue
> ```
> 
> should work, works atleast for me , havent looked at the source code for a year now prolly

I have the same problem, but I cannot modify argument < try_start + 2. This will cause an error in the unpacked pyc. Are there any other solutions? @Svenskithesource

**Comment by Svenskithesource** [comment]
Have you tried setting fake_exit to 6 like I showed above?

**Comment by OwnerCM** [comment]
> Have you tried setting fake_exit to 6 like I showed above?

Yes, I have tried it too, but the output pyc has return value exceptions, as follows:
L.3439 546 LOAD_FAST 'qlines'
           548 RETURN_VALUE
           550 SETUP_EXCEPT 768 'to 768'

 L.1041       632  LOAD_CONST               True
                  634  RETURN_VALUE     
                  636  <41>

**Comment by Svenskithesource** [comment]
This is a known issue that it leaves an extra opcode behind, but it doesn't matter. The code will still work just fine.
