### ISSUE TITLE
NameError: name 'pyarmor' is not defined

### ISSUE THREAD

**Issue by FastVoider** [Svenskithesource/PyArmor-Unpacker#42]
\bypass.py", line 470, in <module>
    exec(code)
  File "<string>", line 1, in <module>
NameError: name 'pyarmor' is not defined

**Comment by Svenskithesource** [comment]
The issue is that the file isn't valid. You should be able to get the file running like normal first. This isn't an issue with the unpacker nor do I give help with these kinds of issues.
