### ISSUE TITLE
the file have license,how can i unpack it

### ISSUE THREAD

**Issue by winfred1984** [Svenskithesource/PyArmor-Unpacker#43]
I hava a python file, it use pyarmor and license to obfuscate, how can i unpacked it. Please give your email, i can send to you.    This is my email  250574994@qq.com

**Comment by Svenskithesource** [comment]
Hello, I have send you an email.

**Comment by OwnerCM** [comment]
> I hava a python file, it use pyarmor and license to obfuscate, how can i unpacked it. Please give your email, i can send to you. This is my email [250574994@qq.com](mailto:250574994@qq.com)

@winfred1984 Have you solved it? I also encountered a similar problem, can you share the solution.
https://github.com/Svenskithesource/PyArmor-Unpacker/issues/48
