### ISSUE TITLE
.py file with license confusion, there was an issue with unpacking using method 3

### ISSUE THREAD

**Issue by OwnerCM** [Svenskithesource/PyArmor-Unpacker#48]
First of all, thank you for providing these solutions.
. py file (Python version 3.10.12), using pyarmor and license to obfuscate, I used method 3 to unpack, and now prompt "Read file license. lic failed, No such file or directory". Do I need to obtain a license to execute?
Also, could you please advise which method is better for confusing such files and whether all three methods require a license file? Looking forward to a reply. Thank you!

**Comment by Svenskithesource** [comment]
PyArmor has a built in license system. You will need a license to run it or you can manually patch the pytransform dll/so. The latter can be done through x64dbg.

**Comment by OwnerCM** [comment]
> PyArmor有一个内置的许可证系统。您将需要一个许可证来运行它，或者您可以手动修补 pytransform dll/so。后者可以通过x64dbg完成。

嗯，我已经拿到

> PyArmor has a built in license system. You will need a license to run it or you can manually patch the pytransform dll/so. The latter can be done through x64dbg.

Thank you for your reply! 
I have obtained the license file and unpacked the pyc file through method 3. The current issue is that Python version 3.10.12 cannot be decompiled using pycdc. I tried to restore the source code through bytecode, but the file is too large and has been abandoned.

**Comment by Svenskithesource** [comment]
This is a common issue and I can not help with that.

**Comment by OwnerCM** [comment]
> This is a common issue and I can not help with that.

@Svenskithesource Thank you. I still want to ask about manually patching the pytransform DLL. I tried using x64dbg and found the keyword "Read file license. lic failed, No such file or directory", but as a beginner, I don't quite understand how to nop. If you happen to have a tutorial, could you please guide me? Thank you again!
File attachment:
[_pytransform.zip](https://github.com/Svenskithesource/PyArmor-Unpacker/files/12327335/_pytransform.zip)

**Comment by Svenskithesource** [comment]
I am sorry but I will not give support about x64dbg, I recommend learning the basics of x64dbg and perhaps looking at my write-up for how I did it for the bootstrap restrict.
