### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ShuRaymond** [Svenskithesource/PyArmor-Unpacker#49]
(3.8) F:\PyArmor_Unpacker_Bypass>python bypass.py demo.py
Preparing the unpacker...
Preparation completed
Initializing the hook
Hook installed
Running the main entry file, continue? (y/n): y
Traceback (most recent call last):
  File "bypass.py", line 418, in <module>
    exec(code)
  File "<string>", line 5, in <module>
ImportError: cannot import name 'pyarmor' from 'pytransform' (F:\PyArmor_Unpacker_Bypass\pytransform\__init__.py)

**Comment by Svenskithesource** [comment]
This error shows that even running the original program wouldn't work. You will need to figure out how to get the original program running before you can unpack it.
