### ISSUE TITLE
Using Method 2 in Python 3.8.16

### ISSUE THREAD

**Issue by OwnerCM** [Svenskithesource/PyArmor-Unpacker#50]
I encountered a. py file encrypted through pyarmor, but this file is not a startup file, it only contains some important functions. I was unable to inject the process through step 3 of method 2 because the file immediately exited the program after being executed through the Python command, and I have not found a suitable method to continue. Please help me, thank you!

Error message through method 2:
![image](https://github.com/Svenskithesource/PyArmor-Unpacker/assets/22722811/60efe99b-173c-4f32-a292-ed0169c142e2)

. py file format:
#Normal mode
From pytransform import pyarmor_ Runtime
Pyarmor_ Runtime()
__ Pyarmor__ (__name__, __file__, b ' x06  x0f...', 2)

**Comment by OwnerCM** [comment]
May I ask if it is necessary to execute the encrypted. py file through the startup file of the project before injecting it? Or is it possible to directly execute the encrypted. py file through the Python command for injection?
I am currently using the second method, but an error message was reported, as shown in the screenshot above. This issue has been bothering me for a long time, and I look forward to your reply. Thank you!

**Comment by Svenskithesource** [comment]
This issue was already discussed in #26 
Please try what was discussed there and explain what you have trouble with if it doesn't work.

**Comment by OwnerCM** [comment]
> This issue was already discussed in #26 Please try what was discussed there and explain what you have trouble with if it doesn't work.

@Svenskithesource I created a module and wrote the following code:
import sys
print('文件名：'+sys._getframe().f_code.co_filename) 
print('函数名：'+sys._getframe(0).f_code.co_name)  
print('调用该函数的函数名字，如果没有被调用，则返回:'+sys._getframe(1).f_code.co_name)
input()

But the error was still reported:
文件名：D:\CZSC\chanlun-pro\src\chanlun\cl_interface.py
函数名：<module>
调用该函数的函数名字，如果没有被调用，则返回:_call_with_frames_removed
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "<string>", line 456, in <module>
NameError: name 'code' is not defined

**Comment by OwnerCM** [comment]
> > This issue was already discussed in #26 Please try what was discussed there and explain what you have trouble with if it doesn't work.
> 
> @Svenskithesource I created a module and wrote the following code: import sys print('文件名：'+sys._getframe().f_code.co_filename) print('函数名：'+sys._getframe(0).f_code.co_name) print('调用该函数的函数名字:'+sys._getframe(1).f_code.co_name) input()
> 
> But the error was still reported: 文件名：D:\CZ\cl_interface.py 函数名： 调用该函数的函数名字:_call_with_frames_removed Traceback (most recent call last): File "", line 4, in File "", line 456, in NameError: name 'code' is not defined

I found that many modules have been changed and the last function called is_ Call_ With_ Frames_ Removed, is this a Pyarmor function?

**Comment by youjunyi** [comment]
@OwnerCM 问题解决了吗？我也遇到了同样的问题

**Comment by OwnerCM** [comment]
> @OwnerCM 问题解决了吗？我也遇到了同样的问题

很遗憾，我也没解决
