### ISSUE TITLE
need some help with the deobfuscation 

### ISSUE THREAD

**Issue by TuNiman1** [Svenskithesource/PyArmor-Unpacker#54]
i tried deobfuscating a program and it didnt fully deobfuscated, it even said:
# WARNING: Decompyle incomplete

i used method 3, i just need help deobfuscating all of it.

**Comment by Svenskithesource** [comment]
There's an important difference between deobfuscating and decompiling. The unpacker spits out deobfuscated bytecode (in a .pyc file), you still need a working decompiler to retrieve the source code. In your case it's an issue of the decompiler you're using and not my unpacker. Currently there aren't any decompilers that work for the more recent Python versions so you're out of luck.
