### ISSUE TITLE
PLEASE FIX YOUR BEAUTIFUL

### ISSUE THREAD

**Issue by kinetikFR** [Svenskithesource/PyArmor-Unpacker#58]
Traceback (most recent call last):
File "C:\Users\polsk\Desktop\unpyarmor\method_1.py", line 10, in
SETUP_FINALLY = opcode.opmap["SETUP_FINALLY"]
~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'SETUP_FINALLY'
PYTHON 311

**Comment by Svenskithesource** [comment]
Python 3.11 has not been tested and is not guaranteed to work. You will need to handle the new way try-except statements work and possibly other stuff as well. Please make a PR if you do so.

**Comment by kinetikFR** [comment]
i dont how to do :(
