### ISSUE TITLE
name "code" is not defind

### ISSUE THREAD

**Issue by Hn-zqz** [Svenskithesource/PyArmor-Unpacker#59]
Hello, I used method 2 to inject the dll file after waiting for the program to run, but I encountered this error
![image](https://github.com/Svenskithesource/PyArmor-Unpacker/assets/81358186/818aecc2-b661-44d5-a462-1ddb847a81ca)

**Comment by Svenskithesource** [comment]
When code is not found it means that this is a paid PyArmor mode, or a version that my unpacker doesn't support. There is no "fix", sorry.
