### ISSUE TITLE
deobfuscate / python 3.6 

### ISSUE THREAD

**Issue by NISKULAT** [Svenskithesource/PyArmor-Unpacker#61]
Hello, svenskithesource. I am facing a problem with deobfuscating a file written in python 3.6 and obfuscated with pyarmor. Method 3 was used, dump was taken, "unknown op_codes error" when trying to decompile. The op_codes are not decompiled to the end, how can I recover them?

**Comment by Svenskithesource** [comment]
As stated in the readme, method 3 only works for Python 3.9.7+. It's expected to fail in Python 3.6. I would recommend to use a different method, but I can't guarantee they work for 3.6 as I've never used it on this version before myself.
