### ISSUE TITLE
shit not working

### ISSUE THREAD

**Issue by Alangopro** [Svenskithesource/PyArmor-Unpacker#64]
tested all the injectors i could found and there is nothing dumping from the exe file
![image](https://github.com/user-attachments/assets/e690cd9a-b10c-4deb-8ee2-dfe5bda38eec)
![image](https://github.com/user-attachments/assets/0329abd7-434f-41f0-94e8-d51fecc227df)

and i can't even use proccess hacker becouse that shit app would crash due to detection of it.

the exe is at https://nighty.one/download < no acc needed

**Comment by Svenskithesource** [comment]
Nighty uses a newer and paid version of PyArmor, which isn't supported by my deobfuscator.
